### ISSUE TITLE
Doesn't work with custom jsdom

### ISSUE THREAD

**Issue by sheerun** [kentcdodds/dom-testing-library#100]
- `dom-testing-library` version: 3.5.1
- `react` version: 16.4.1
- `node` version: 10.4.1
- `npm` (or `yarn`) version: yarn 1.7.0

### Relevant code or config:

Usual installation,

```
"testEnvironment": "node",
```
as jest configuration, then something like following in tests:

```js
import { getByText } from 'dom-testing-library'

it('Suggests cities to search by', async () => {
  const container = createJSDOM(...)
  getByText(container, 'foobar')
})
```

### What you did:

Tried to use dom-testing-library with node environment in Jest + creating own jsdom instance in a helper and passing it to dom-testing-library.

### What happened:

  ● Test suite failed to run

    ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/mutationobserver-shim/dist/mutationobserver.min.js:3:1)
      at Object.<anonymous> (node_modules/dom-testing-library/dist/wait-for-element.js:8:1)
      at Object.<anonymous> (node_modules/dom-testing-library/dist/index.js:32:23)

### Reproduction:

As above, enable node jest environment and try to use dom-testing-library with some custom container

### Suggested solution:

check if shim is loaded on given container and install it only then? generally something to support no global window object in jest environment

**Comment by sheerun** [comment]
Also maybe quick not why I'm doing this. From the jsdom documentation:

> Note that we strongly advise against trying to "execute scripts" by mashing together the jsdom and Node global environments (e.g. by doing global.window = dom.window), and then executing scripts or test code inside the Node global environment. Instead, you should treat jsdom like you would a browser, and run all scripts and tests that need access to a DOM inside the jsdom environment, using window.eval or runScripts: "dangerously".

**Comment by kentcdodds** [comment]
What if you do this:

```javascript
it('Suggests cities to search by', async () => {
  const container = createJSDOM(...)
  const { getByText } = require('dom-testing-library')
  getByText(container, 'foobar')
})
```

**Comment by kentcdodds** [comment]
I'm happy to accept a PR for this if it doesn't make a huge impact on the codebase or any impact on the API, but I don't think anyone is going to work on it. Feel free to open a PR though. I'll close this though as there's a workaround.

**Comment by sheerun** [comment]
@kentcdodds I think it's bad manners to close issue before allowing to respond

You solution still doesn't work if you put `"testEnvironment": "node"` in Jest configuration. Here's example to reproduce:

```es6
it('fails', async () => {
  const { JSDOM } = require('jsdom')
  const { getByText } = require('dom-testing-library')
  const container = new JSDOM('<html><bodyu><div></div>foobar</body></html>').window.document
  getByText(container, 'foobar')
})
```

I still get:

    ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/mutationobserver-shim/dist/mutationobserver.min.js:3:1)
      at Object.<anonymous> (node_modules/dom-testing-library/dist/wait-for-element.js:8:1)
      at Object.<anonymous> (node_modules/dom-testing-library/dist/index.js:32:23)

Could you reopen?

**Comment by kentcdodds** [comment]
Sorry, but this library requires that you have the DOM globally accessible in the environment in which you are testing. I think this would work:

```javascript
it('does not fail', async () => {
  const { JSDOM } = require('jsdom')
  const {window} = new JSDOM('<html><bodyu><div></div>foobar</body></html>')
  global.window = window
  const container = window.document
  const { getByText } = require('dom-testing-library')
  getByText(container, 'foobar')
})
```

I realize that jsdom recommends against this but I disagree with it and either way Jest's default implementation is to use jsdom to simulate the browser environment and it seems to work great for everyone using this library.

In any case, this library makes the assumption that your environment is a DOM-based environment and it's your responsibility to make that the case. I don't want to add a bunch of stuff to handle edge cases like this.

I don't mean to be impolite or rude, I'm just trying to manage the issues in the project and I was 99% certain that we aren't going to do anything about this issue and we can always re-open it. Closing issues is not personal.

**Comment by sheerun** [comment]
bummer

**Comment by kentcdodds** [comment]
As I said:

> I'm happy to accept a PR for this if it doesn't make a huge impact on the codebase or any impact on the API

Otherwise, it's outside of the scope of the library.

**Comment by alexkrolick** [comment]
I think the only thing that breaks at import time is https://github.com/kentcdodds/dom-testing-library/blob/master/src/wait-for-element.js, and at runtime the window dependency may error in the `wait` util.

You should be able to get around this if you are just using the queries by doing:

```js
import * as queries from 'dom-testing-library/dist/queries'
```

https://unpkg.com/dom-testing-library@3.5.2/dist/queries.js

**Comment by TidyIQ** [comment]
Hi @kentcdodds , are you able to explain how to run the tests in node environment? I included `testEnvironment: "node"` in my jest.config.js file however all my tests are returning the error `ReferenceError: document is not defined`. Is there something else I need to do? I looked in the docs and couldn't see anything about it.

**Comment by alexkrolick** [comment]
Remove `testEnvironment: "node"`, you need a JSDOM environment, which is the default in jest.

**Comment by TidyIQ** [comment]
Doesn't this commit referenced a few comments up indicate that you can now run it in node environment though? 

https://github.com/testing-library/dom-testing-library/commit/1b12385032841c14633c5061f3ab38f938df4c03

**Comment by alexkrolick** [comment]
@TidyIQ I don't think that's the case anymore - https://github.com/testing-library/dom-testing-library/blob/master/src/helpers.js#L18

**Comment by kentcdodds** [comment]
If it's easy enough to fix them we should fix it. But I don't personally see this as a big priority.

**Comment by sheerun** [comment]
@kentcdodds I spent much time to implement this feature and even made regression tests specifically to prevent this situation, and then @Tolsee commits removes them: https://github.com/testing-library/dom-testing-library/commit/1727a49cdbb9c4da412e38724a50eff2a4b95667#diff-2d0cd5d10b9604941c38c6aac608178a

If you or don't see if as big priority please at least don't remove tests when implementing features... This is breaking change for me and my application

**Comment by kentcdodds** [comment]
The tests were causing trouble. I can't remember what, but they were pretty annoying. If prefer something much not lightweight. I may be able to work on it this afternoon.

**Comment by sheerun** [comment]
They were "annoying" on purpose: to prevent this situation. When they were removed this library immediately stopped supporting custom jsdom. Making new utilities that support custom jsdom isn't that hard but requires little efford and these tests ensure nobody takes shortcuts like in this case. If you want to make them lightweight please ensure they new tests also cover all utilities.

**Comment by kentcdodds** [comment]
The market share of people using this utility without a global jsdom environment is about 0.001% of users. So I'm sorry if I'm not bending over backward to make sure I'm not breaking your use case.

**Comment by sheerun** [comment]
How do you know this percentage is true? Even if it was it's not fair to break already working code. If you don't want to put effort for implementing new tools at please at least leave old tools working. I don't know where your anger comes from

**Comment by sheerun** [comment]
(By all utilities I meant all utilities that were already supported, not new ones)

**Comment by kentcdodds** [comment]
I'm not going to argue about this with you. I'm going to set a lightweight test in place so we hopefully don't break things in the future. If that's no enough for you then feel free to use an old version of the library or maintain a fork.
