### ISSUE TITLE
Jest async matchers

### ISSUE THREAD

**Issue by gnapse** [kentcdodds/dom-testing-library#11]
There seems to be an ongoing effort in the jest library to add support for [async matchers](https://github.com/facebook/jest/pull/5919). I wonder how that affects the need to use something like  this library's `wait` utility.

**Comment by kentcdodds** [comment]
We could potentially add matchers (to `jest-dom`) that support async matchers. But I see `wait` as useful beyond just assertions but waiting for some state to be true and then continuing on with further assertions and actions. So we'll probably keep it around.

For now I'll go ahead and close this and we can discuss async matchers more in jest-dom :+1: Thanks!
