### ISSUE TITLE
Problem with typings

### ISSUE THREAD

**Issue by jenovs** [kentcdodds/dom-testing-library#112]
- `dom-testing-library` version: 3.8.1

### Problem description:

Typings for query by role are named with a `T` inside (`queryByTRole`, `queryAllByTRole`, `getByTRole`, `getAllByTRole`) which makes TS compiler fail.

### Suggested solution:

Rename exports in `typings/queries.d.ts`.

**Comment by kentcdodds** [comment]
Hi @jenovs, thanks!

Could you make a PR to fix that please?

**Comment by jenovs** [comment]
Hi @kentcdodds,
I'm trying to push my PR, but I'm getting this error:
```
git push --set-upstream origin pr/fix-typings

ERROR: Permission to kentcdodds/dom-testing-library.git denied to jenovs.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
What am I doing wrong?

**Comment by jenovs** [comment]
I ended up editing the file on GitHub.

**Comment by kentcdodds** [comment]
That's fine.

In the future, maybe this'll be helpful to you :) http://makeapullrequest.com
