### ISSUE TITLE
getByLabelText does not match when id has a "." in the string.

### ISSUE THREAD

**Issue by ngbrown** [kentcdodds/dom-testing-library#12]
I had an element that looks like this:

```html
<label for="activity.username">Username</label>
<input id="activity.username" />
```

and calling: `getByLabelText('Username')` throws because it won't find the <input /> with an id of `activity.username`.  Having a period in the `id` is valid HTML.

The reason is that on this line:

https://github.com/kentcdodds/dom-testing-library/blob/4bf26d70eda829ca0470c79952f53f5d51ab423b/src/queries.js#L27

the CSS selector `#` needs to be escaped for a characters that are not valid CSS labels.  In this case it is trying to run `container.querySelector('#activity.username')` but that needs to be escaped to `container.querySelector('#activity\\.username')`.  (double slash to escape in javascript, so the actual string would only have one slash)  (see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#Escaping_special_characters)).

An alternative would be to use the `[id='activity.shift']` selector, as that finds the element without escaping:

So the whole line would be:

```js
return container.querySelector(`[id='${label.getAttribute('for')}']`)
```

**Comment by kentcdodds** [comment]
Sure!

**Comment by alexkrolick** [comment]
#22 should have closed this it looks like
