### ISSUE TITLE
Readme: the example of getByText is not accurate

### ISSUE THREAD

**Issue by ruffle1986** [kentcdodds/dom-testing-library#122]
Before getting started, let me say thank you for all the hard work to make devs` life easier with testing! Well done! 🍻 

### Problem description:

The example of `getByText` is incorrect and misleading in the readme. 

It says running the following script would produce the result commented out above the script.

```js
// <a href="/about">About ℹ️</a>
const aboutAnchorNode = getByText(container, 'about')
```

Since `options.exact` is true by default, it won't find the anchor element unless we change the code a bit (see the `Suggested solution:` section). 

### Suggested solution:

I see three options here to solve this:

A:
```js
// <a href="/about">About ℹ️</a>
const aboutAnchorNode = getByText(container, 'About ℹ️')
```

B:
```js
// <a href="/about">About ℹ️</a>
const aboutAnchorNode = getByText(container, 'about', {
  exact: false
})
```

C:
```js
// <a href="/about">About ℹ️</a>
const aboutAnchorNode = getByText(container, /about/i)
```

Let me know which one is preferred and I'll open a PR on this.

Cheers!

**Comment by gnapse** [comment]
I'd say option C.

**Comment by sompylasar** [comment]
A or D:
```
// <a href="/about">About ℹ️</a>
const aboutAnchorNode = getByText(container, /^About\s+/)
```
More precise is better IMHO to catch if the text changes unintentionally.

**Comment by kentcdodds** [comment]
Let's go with C. That's what I do in my own stuff because the user doesn't care about the case of the text 👍

Thanks!

**Comment by sompylasar** [comment]
> Let's go with C. That's what I do in my own stuff because the user doesn't care about the case of the text 👍

The user doesn't, but the UI designers might...

**Comment by kentcdodds** [comment]
Fair point. It's trade-offs. I'd still suggest generally ignoring case.

**Comment by gnapse** [comment]
+1 to ignore case, plus this for our README we're talking about here, people can still use the exact string if they like and it's documented.

(BTW, capitalization can be achieved via css, and there's nothing we can do about that from a testing POV)

**Comment by Gpx** [comment]
How about adding A and C and explaining the differences?

**Comment by ruffle1986** [comment]
I agree with @Gpx. It may be worth to mention both A and C. I'll open a PR including this and if you still don't feel it, I'll update it accordingly.

**Comment by ruffle1986** [comment]
> (BTW, capitalization can be achieved via css, and there's nothing we can do about that from a testing POV)

@gnapse Very good point. We should point it out too.

**Comment by kentcdodds** [comment]
The explanation should probably be in a FAQ.
