### ISSUE TITLE
Make data-testid attribute configurable.

### ISSUE THREAD

**Issue by BenjaminEckardt** [kentcdodds/dom-testing-library#128]
First of all, thanks a lot for this library. I really like the approach of using the information the user actually perceives to select elements that are about to be tested.

The only feature that seems to differ from that approach is the `data-testid`. Although I also like this feature, I have a request for improvement.

### Describe the feature you'd like:
Currently the `data-testid` attribute is hard coded.

https://github.com/kentcdodds/dom-testing-library/blob/master/src/queries.js#L153

I would like to have a possibility to pass the attribute as a configuration.
The benefit I see is that you can decouple the used attribute from the used testing library. This reduces the locking to this specific library. Besides that it also gives you the possibility of using this library also for existing UIs that rely on a different attribute for the same purpose.

Since it's just a change of the selector I don't see any conflict with the philosophy of this library.

### Describe alternatives you've considered:
Alternative would be applying changes to all existing UIs whenever I change the testing library. Although this might often be achievable within an manageable amount of time, I would like to avoid these kind of unnecessary changes.

**Comment by gnapse** [comment]
This seems to be a duplicate of #76, where you can see some suggestions about how to deal with this without requiring chanting the library.

**Comment by BenjaminEckardt** [comment]
Seems like i missed that one. Sorry for the duplicate. Thanks for the reply.

**Comment by psyshush** [comment]
the ability has been added to the library, see [here](https://testing-library.com/docs/dom-testing-library/api-configuration)
