### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/dom-testing-library#131]
In [this build](https://travis-ci.org/kentcdodds/dom-testing-library/builds/442383661)

```
[test] 
[test]     Expected: 60
[test]     Received: 82
[test] 
[test]       21 |   // if it's greater than 50 then `wait` used a timeout
[test]       22 |   // but it should have resolved sooner. It really should be 0
[test]     > 23 |   expect(after - before).not.toBeGreaterThan(60)
[test]          |                              ^
[test]       24 |   expect(spy).toHaveBeenCalledTimes(1)
[test]       25 | })
[test]       26 | 
[test] 
```

I think that test should probably be made more reliable somehow... We can't release until the build is green though. Anyone wanna help here?

**Comment by alexkrolick** [comment]
Maybe using jest timer mocks?

**Comment by kentcdodds** [comment]
Yeah, that'd probably be best here.

**Comment by Gpx** [comment]
Is this issue still valid? I tried to run the tests several times in my machine and they never failed

**Comment by kentcdodds** [comment]
That's the trouble with time-dependant tests. You often wind up with issues on slower machines that you can't reproduce on faster ones.

**Comment by weyert** [comment]
Think this ticket can be closed now?
