### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by gnapse** [kentcdodds/dom-testing-library#133]
Thanks for dom-testing-library, the real hero behind react-testing-library (because React is just an implementation detail 😉)

Also thanks for the opportunity to collaborate, and thanks for jest-dom. Thanks for everything you do to encourage testing. It makes web development better, which makes the world a better place.

**Comment by kentcdodds** [comment]
Wow! I should be thanking you for all the work you've done on all the projects you've mentioned. THANK YOU!
