### ISSUE TITLE
Types for queryByTestId not correct

### ISSUE THREAD

**Issue by ssylvia** [kentcdodds/dom-testing-library#135]
- `dom-testing-library` version: 3.11.2

### Relevant code or config:

![screen shot 2018-10-23 at 8 27 28 am](https://user-images.githubusercontent.com/1211360/47360474-9b638400-d69d-11e8-8a4d-4d3665fed9c3.png)

### What you did:

Used `queryByTestId` in typescript

### What happened:

VSCode gives error that more arguments are expected

### Problem description:

Looks like `queryByTestId` uses the `queryByAttribute` type: https://github.com/kentcdodds/dom-testing-library/blob/master/typings/queries.d.ts#L52, even thought the `attribute` argument is automatically bound: https://github.com/kentcdodds/dom-testing-library/blob/master/src/queries.js#L153.

### Suggested solution:
Add a new type or pick the keys off the `queryByAttribute` type.

**Comment by ssylvia** [comment]
Looks like this might be a regression from 3.11.1 PR #130.

**Comment by alexwendte** [comment]
I do not understand typescript very well, but it looks like the arguments for the `queryBy` and `getBy` functions are being inferred. https://github.com/kentcdodds/dom-testing-library/blob/f29f551b1d9b031b0d8cf2d2dc436eae229ecc1d/typings/get-queries-for-element.d.ts#L4-L10The `queryByAltText` type is broken as well.

**Comment by jgoz** [comment]
This is happening because the argument order for `attribute` and `container` is wrong on `QueryByAttribute`. I'll open a PR.
