### ISSUE TITLE
Configurable data-testid

### ISSUE THREAD

**Issue by davidgilbertson** [kentcdodds/dom-testing-library#136]
### Describe the feature you'd like:

The ability to define what attribute will be used to denote a test id.

For example, an organisation may have a code base where `data-test-id` is currently used, but `dom-testing-library` will look for an attribute of `data-testid`. If they want to begin using `dom-testing-library`, they would need to universally change all test IDs, which prevents an incremental roll-out.

### Suggested implementation:

Usage might be something like:

```js
// in global test setup
import domTestingLibrary from 'dom-testing-library';

domTestingLibrary.config({ testIdString: 'data-test-id' });
```

E.g. Cypress does it like so: https://docs.cypress.io/api/cypress-api/config.html#Syntax
Jest does it slightly more strangely: https://jestjs.io/docs/en/configuration.html#defaults

Another option would be a config file (standalone rc file or package.json prop), but that seems like overkill, and there would be no option to do it per-file which might be useful to some.

And internally, this could perhaps be held in a `config.js` module that is loaded into `queries.js` and referenced. I don't believe there would be any performance impact.

### Describe alternatives you've considered:

I can't think of any alternatives. We actually have an internal component library (separate npm package) and it defines the attribute name `data-test-id` and no option to change it because it's shared across many projects.

### Teachability, Documentation, Adoption, Migration Strategy:

As an opt-in to change the default, it wouldn't need to be a breaking change, docs should be minimal.

P.S.: awesome work on this library.

**Comment by alexkrolick** [comment]
The recommended approach right now is to use the exported query helpers to define your own testId query: https://github.com/kentcdodds/react-testing-library#getbytestidtext-textmatch-htmlelement

**Comment by davidgilbertson** [comment]
Ah, I didn't realise this had been brought up so many times so recently!

(Maybe that's a sign it's a good idea? 😉 )

I see the example in the docs now, thanks for that.
