### ISSUE TITLE
getByName(attribute) feature request

### ISSUE THREAD

**Issue by yohaydy** [kentcdodds/dom-testing-library#143]
**Describe the feature you'd like:**
Some text `inputs` and especially `select` tags may not have associated label.
To select them, you need to add testid or labels.

**Suggested implementation:**
It would be nice to query those elements by `name` attribute.
I think name attributes are less prone to changes than class names, so it is fine to rely on them.

Any thoughts for/against this ?

**Comment by alexkrolick** [comment]
Closing with the explanation from the PR: 

`name`, `id`, `className`, etc. are not accessible selectors - they are not visible to the user and not selectable by assistive technology like screensreaders or built-in tab navigation. testid is the designated "escape hatch" if you need to do something like this.

You can add these queries to your own code if you want by doing something like this: see #146 

If you only want to query for this infrequently, remember that regular DOM APIs work fine: document.querySelectorAll("[name=${myName}]" `)
