### ISSUE TITLE
getByValue cannot get element by dynamically assigned value

### ISSUE THREAD

**Issue by eunjae-lee** [kentcdodds/dom-testing-library#158]
- `dom-testing-library` version: 3.12.4
- `react` version: not using with react
- `node` version: 8.11.1
- `npm` (or `yarn`) version: npm 5.6.0

### Relevant code or config:

```js
test('get element by its dynamically assigned value', () => {
  const {getByValue, queryByValue, getByTestId} = renderIntoDocument(`
  <div>
    <input placeholder="name" type="text" data-testid="name" />
  </div>
  `)
  getByTestId('name').value = 'Norris'
  expect(getByValue('Norris').placeholder).toEqual('name')
  expect(queryByValue('Norris').placeholder).toEqual('name')
})
```

### What you did:

There's an `input` element (without initial `value` attribute). I put some value in it with JavaScript. 

### What happened:

`getByValue` or `queryByValue` cannot get the element.

```
  ● get element by its dynamically assigned value

    Unable to find an element with the value: Norris.
```

### Problem description:

According to `queryAllByAttribute` at `src/query-helpers.js`, it's executing some code like

```
container.querySelectorAll("[value]")
```

Since the `input` element didn't have any `value` attribute at the first place, this query cannot get it.

### Suggested solution:

It should still get `input` element unless this behaviour is intended.
Querying it with `[value]` didn't work. Getting value with `node.getAttribute("value")` didn't work either. So I guess the following code could solve the problem.

```
Array.from(container.querySelectorAll("input")).filter(node => node.value === value)
```

Let me know what you think!

**Comment by alexkrolick** [comment]
The .value setter/getter and the DOM attribute aren't necessarily in sync (see [Codepen](https://codepen.io/alexkrolick/pen/NELEKE?editors=1011
)), so you'd probably need to either concat the results of both the current querySelectorAll and the proposed filtered DOM traversal, and maybe dedupe the results with some documented hierarchy (probably preferring the dynamic `.value`).
