### ISSUE TITLE
Unable to fire event on document

### ISSUE THREAD

**Issue by arvigeus** [kentcdodds/dom-testing-library#159]
- `react-testing-library` version: 5.3.0
- `react` version: 1.6.6.3
- `node` version: 8.11.3
- `yarn` version: 1.12.3

### Relevant code or config:

```js
fireEvent.keyDown(document.body, {
  key: "Escape",
  keyCode: 27,
  which: 27
});
```

### What happened:

TypeError: Cannot read property 'defaultView' of null

### Suggested solution:

https://github.com/kentcdodds/dom-testing-library/blob/master/src/events.js#L324
Should handle document and window elements (possibly in more places)

**Comment by kentcdodds** [comment]
Hmmm.... Can you dig deeper because `document.body.ownerDocument.defaultView` is `window`:

<img width="516" alt="screen shot 2018-11-22 at 10 32 42 am" src="https://user-images.githubusercontent.com/1500684/48917043-12796d00-ee42-11e8-8b06-1039c34bc3fe.png">

**Comment by alexkrolick** [comment]
Not able to reproduce this error - see https://github.com/alexkrolick/repro-document-fire-event/blob/master/src/__tests__/index.test.js

Please provide a minimal reproduction in Codepen or a repo if you can come up with one

It seems possible that this error is due to something else, such as the node being queried being undefined/null

**Comment by abe4mvp** [comment]
I am getting this same issue but when im trying to fire an event on document.
`fireEvent.keyDown(document, { key: 'ArrowRight'});`

also confirmed that 
`document.ownerDocument`  is null in the browser

**Comment by kentcdodds** [comment]
Hey @abe4mvp,

I think that it would be reasonable to change this:

https://github.com/kentcdodds/dom-testing-library/blob/ab29a47386394fee16db700db8cfd5a6ac03c33e/src/events.js#L332

to this:

```javascript
// if the node does not have an owner document, then it probably _is_ the owner document
const window = (node.ownerDocument || node).defaultView
```

If you would be willing to [make a pull request](http://makeapullrequest.com) for that (including a test) then we can merge it and you should be good to go :)
