### ISSUE TITLE
Ship ES5-compatible bundles

### ISSUE THREAD

**Issue by benelliott** [kentcdodds/dom-testing-library#160]
### Describe the feature you'd like:

Hi, would you be open to shipping Babel-transpiled ES5 bundles of this library? We are trying to use it over at https://www.github.com/netbasal/spectator but have trouble with IE11 compatibility because of the use of arrow functions in the current UMD bundles.

### Suggested implementation:

Configure Babel to support IE11.

### Describe alternatives you've considered:

n/a

### Teachability, Documentation, Adoption, Migration Strategy:

n/a

**Comment by NetanelBasal** [comment]
+1

**Comment by kentcdodds** [comment]
Dang it. It looks like some of our dependencies are not compiling themselves. That's pretty annoying. We'll need to figure out how to configure babel to compile `node_modules`.

This change will need to happen in `kcd-scripts`. Would you be willing to look into what must be done (probably [here](https://github.com/kentcdodds/kcd-scripts/blob/8337bbd16fa4f964f688975f3c510d4705c94932/src/config/rollup.config.js#L145-L150)) to make that happen?

**Comment by benelliott** [comment]
It looks like these arrow functions are coming from `pretty-format`, which does ship its own `build-es5` module. Maybe if that was specifically loaded instead you wouldn't have to worry about reconfiguring Babel to compile your dependencies?

**Comment by kentcdodds** [comment]
Alrighty, this has been fixed! Big thanks to @fobbyal in https://github.com/kentcdodds/kcd-scripts/pull/72

**Comment by NetanelBasal** [comment]
Awesome, thanks! Will test it soon and let you know.
