### ISSUE TITLE
Add queryByTag / queryAllByTag ?

### ISSUE THREAD

**Issue by FredyC** [kentcdodds/dom-testing-library#167]
### Describe the feature you'd like:

I am a bit surprised that this utility function is not present. I mean it's surely easy to do `container.querySelector('input')`, but it would feel much more concise if I could just `queryByTag('input')` without messing with `container` directly not even mentioned `getByTag` :)

My only guess why this wasn't added is some assumption that it would lead to testing implementation details? One could argue about that. The resulting DOM is what the test cares about, right?

### Teachability, Documentation, Adoption, Migration Strategy:

Non breaking change, pretty straightforward I think.

**Comment by gnapse** [comment]
My take is that, as you say, this is a bit of an implementation detail. The end user does not know or care about what tag an element is in general. That's why most `queryBy*` functions provided try to find elements by features that are prominent to a would-be actual user experiencing the page via a web browser or screen reader. I think `queryByTestId` is the only counter example.

**Comment by FredyC** [comment]
I see. It's a thin line for sure. For example, when a component is wrapping input element it would feel weird write tests pretending there is no actual input underneath. Ultimately, you need to fire events on that particular element and that alone can be seen as an implementation detail :)

The `queryByTestId` is surely another way, but you need to know what kind of element it is anyway, right?

**Comment by gnapse** [comment]
Yes, `input`s are maybe a special case, but the feature you're requesting is too broad, allowing to select by any tag, which could be abused. Maybe there should be a way to query form elements. `jest-dom` has [something like that](https://github.com/gnapse/jest-dom#tohaveformvalues) to assert expected form values. But it does not work for the general purpose of also interacting with the elements programmatically.

**Comment by kentcdodds** [comment]
We do have a way to query form elements: `getByLabelText`. That's what I recommend using. We understand that sometimes the built-in queries aren't enough, but that's why you get the container. Yes, interacting with an input DOM node is a bit of an implemention detail, but we make tradeoffs for practicality. This situation doesn't warrant a special API. I WANT it to be awkward to select by tag name. You generally should use another query for that or the test ID add an escape hatch. 

I don't think we'll do this. Thank you anyway!

**Comment by FredyC** [comment]
Ok, I understand. I am kinda writing my first tests with this library and it happens that it's the component wrapping an input so I was a bit confounded how to approach that.

> With `queryByTestId` you do not need to hard code in your test what kind of element it is. You can start with a `<button>` and later decide you need a `<div role="button" tabIndex={0}>` for some reason. As long as you keep the `data-testid` attribute in place, your test is good to go.

Buttons are easy I suppose as it's mostly about clicking on them. With input, if I want to eg. forcefully set its value, there is no easy path around that.

**Comment by kentcdodds** [comment]
The "easy path" for querying for an input is to use `getByLabelText`. For buttons use `getByText`. Is there a reason that doesn't work for you?

**Comment by gnapse** [comment]
Why not? If you have an `input type="text"` with a `data-testid`, and later you change it to a `textarea`, would it break the way you set the value?

Also, as Kent mentioned above, `getByLabelText` should work too. After all, a real user will interact with the input based on how its labeled, which is what tells them what the input is for. And it will still work if you change an input to later be a text area. Nothing about that still holds if you grab the input by its tag name (which in the case of inputs also includes radio buttons, checkboxes, etc).

**Comment by FredyC** [comment]
Yeah, `getByLabelText` works in an ideal world, but when our designer wants inputs with placeholders and no labels around it's kinda hard to argue about that. I could add a hidden label there, but that feels like I am doing it just to satisfy tests which never felt right to me (same reason why I don't like data-testid much). Yea sure, accessibility argument ... we are targetting specific audience where it doesn't need to be taken care of so it's not on the list really.

> Why not? If you have an `input type="text"` with a `data-testid`, and later you change it to a `textarea`, would it break the way you set the value?

Sure, but in case of something more esoteric like div with own caret animated through CSS and handling all keyboard and stuff manually it would break. It's not that unrealistic, been there, done that :)

**Comment by alexkrolick** [comment]
The goal of this library is to provide a user-centric approach to testing webapps - it is not to to become a DOM traversal library. For that you can use `document.querySelector` - it works fine in JSDOM.
