### ISSUE TITLE
Issue update the input value when using `useState` hook

### ISSUE THREAD

**Issue by Pau1fitz** [kentcdodds/dom-testing-library#170]
I am having issues update the input value when using `useState` hook.

- `dom-testing-library` version:^5.2.3
- `react` version:^16.7.0-alpha.2
- `node` version:v10.14.1
- `npm` (or `yarn`) version:1.12.3

### Relevant code or config:

```js

const LoginForm = () => {
    const [form, setValues] = useState({
        username: '',
        password: '',
    });

    const updateField = (e: React.FormEvent<HTMLInputElement>): void => {
        setValues({
            ...form,
            [e.currentTarget.name]: e.currentTarget.value,
        });
    };

    return (
        <>
            <form onSubmit={performLogin}>
                <label htmlFor="username">
                    Username
                </label>
                <input
                    type="text"
                    value={form.username}
                    onChange={updateField}
                />

                <label htmlFor="password">
                    Password
                </label>
                <input
                    type="password"
                    value={form.password}
                    onChange={updateField}
                />
                <button type="submit">Login</button>
            </form>
        </>
    );
}
```

### What you did:

I am trying to update the username and password but to no avail. My code looks like the following:

```
import React from 'react';
import { render, getByLabelText, getByText } from 'react-testing-library';

it('renders the Login Form and allows a user to login', async () => {
    const usernameInput = getByLabelText(/username/i);
    const passwordInput = getByLabelText(/password/i);
    usernameInput.value = 'Mary';
    passwordInput.value = '****';
    getByText(/Mary/i);
});

```

### What happened:

<img width="947" alt="screenshot 2018-12-07 at 17 25 13" src="https://user-images.githubusercontent.com/6873736/49662940-1366ed00-fa45-11e8-977f-14437c32f6dc.png">

### Reproduction:

Here is a code sandbox - https://codesandbox.io/s/7j7o12qv96

**Comment by gnapse** [comment]
You should update them like this:

```js
fireEvent.change(inputField, { target: { value: 'new value' } })
```

instead of

```js
inputField.value = 'new value'
```

Have you tried that? I recall that the latter is no longer supported, but now reviewing the README I see that there are still examples in it using this way. If you confirm the first way of doing it in the examples above works, then maybe the README needs to be updated.

**Comment by Pau1fitz** [comment]
That works 

`fireEvent.change(inputField, { target: { value: 'new value' } })`

**Comment by gnapse** [comment]
Also, I'm not sure `getByText` would find an `input` element with that text being its value. `getByText` is meant to find elements that have that `textContent`. That could be an issue here as well.

**Comment by Pau1fitz** [comment]
Tbh, I am testing a mock api call so I wanted to check the values were being sent to the mocked api call. I just put the `getByText` there for this question.
