### ISSUE TITLE
Need some instructions on how to use this library

### ISSUE THREAD

**Issue by zydjohnHotmail** [kentcdodds/dom-testing-library#177]
Hello:
I have a simple HTML file, running from local web server:
http://localhost/index.html

```html
<title>index</title>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script>
<script type="text/javascript">
$(document).ready(function count1() {
  var counter = 1;
  setInterval(function() {
    $(".single").text(counter++);
  }, 1000);
});
</script>
<script type="text/javascript">
$(document).ready(function count2() {
  var counter = 200;
  setInterval(function() {
    $(".double").text((counter += 2));
  }, 2000);
});
</script>
```

This setups a HTML file with two JavaScript functions. The first one, `count1()` shows an increasing number from 1 with step of 1, sleeps one second each time.
The second one, `count2()`, shows an increasing number from 200 with step of 2, and sleeps two seconds each time.

Both functions generate dynamic text inside different elements, but they are both children from their parent node.

Now I can use Chrome DevTools to run some JavaScript.

I think dom-testing-library is a good JavaScript library, so I want to use it to write some JavaScript to get the dynamic text generated by the 2 JavaScript functions in the above simple HTML file.

However, I don't know how I can use Chrome DevTools to use 3rd party JavaScript library, also, no experience on how to use dom-testing-library to listen to MutationObserver events.

Please provide some instructions on how to use 3rd party JavaScript library and some dom-testing library to catch the dynamic text generated by the JavaScripts from this simple HTML.

Thanks,

**Comment by kentcdodds** [comment]
Hi @zydjohnHotmail,

I'm not totally sure I understand your use case, but you can include dom-testing-library on your page in a similar way that you include jQuery:

```html
<script src="https://unpkg.com/dom-testing-library@3.13.1/dist/dom-testing-library.umd.js"></script>
```

Then you can use the global variable `DomTestingLibrary`.

I hope that's helpful.

If you have further questions, please direct them to [spectrum](https://spectrum.chat/react-testing-library).
