### ISSUE TITLE
Consider listing getAll queries explicitly in the API documentation

### ISSUE THREAD

**Issue by gregtatum** [kentcdodds/dom-testing-library#200]
### Problem description:

As a user, I would like quick access to the API documentation.

> Sidebar at: https://testing-library.com/docs/api-queries
> <img width="187" alt="image" src="https://user-images.githubusercontent.com/1588648/52130636-54701d80-2600-11e9-8b17-249e2c810f47.png">

The sidebar lists all of the queries that are available, and is an easy reference when I'm deep in the middle of writing tests. However, the `getAll` functions are not explicitly listed. Since I'm writing tests, I'm looking to quickly get the information I need to accomplish my task, and missed the notices and sub-paragraphs about the `getAll` functions.

As a new user, I wrote the following in a test, since I didn't realize that these convenience functions existed.

```js
verticalIndicators.querySelectorAll('[data-testid="vertical-indicator-line"]')
```

### Suggested solution:

List all available API methods in the sidebar.

**Comment by kentcdodds** [comment]
Thanks for the suggestion @gregtatum. Could you please file this issue on the docs repo? https://github.com/alexkrolick/testing-library-docs/issues

Thanks!
