### ISSUE TITLE
adding queryByName/queryAllByName

### ISSUE THREAD

**Issue by adnasa** [kentcdodds/dom-testing-library#214]
### Describe the feature you'd like:

Hey
thanks for this project.
I was wondering if there was a strong reason to not support `(query|get)AllByName` or if this is a missing feature. At the moment, we are adopting `dom-testing-library` in our project and I've run into concerns where it has forced me to adapt my implementation.

Some pain points

1. I have to apply `data-testid` when I don't have to otherwise e.g in forms
2. unless an external library supports accepting `data-testid`, I have to wrap component I desire to test and add in `data-testid`

### Suggested implementation:

if there are no reasons against it, I would like to propose we add support to select by `name` (queryByName)

I [tried this out](https://github.com/adnasa/dom-testing-library/compare/master...adnasa:adnasa-query-by-name) and worked out fine, and would be happy to follow this up with a PR

### Describe alternatives you've considered:

on top of wrapping components with e.g `<div data-testid="my-id"/>`, and using `getBySelectText`/`getByPlaceholderText` has fulfilled my needs.

### Teachability, Documentation, Adoption, Migration Strategy:

TBD

**Comment by kentcdodds** [comment]
Is there a reason your forms aren't using labels? A form without a label is not nearly as accessible.

**Comment by adnasa** [comment]
Hello
yes we do use labels 😅 
however good call because we do use `htmlFor` and I simply didn't pay close attention to `queryLabelByText` 🤦‍♂️ 

This block gave me the info I was looking for and would have solved a lot of cases.

https://github.com/kentcdodds/dom-testing-library/blob/2cda6a77da4e5375f224acde566cc7a7da840472/src/queries.js#L43-L50

oh well, this was an easy one 😅 
see you in react@AMS
