### ISSUE TITLE
Docs for query APIs should not have the container argument listed.

### ISSUE THREAD

**Issue by akatechis** [kentcdodds/dom-testing-library#219]
- `react-testing-library` version: 6.0.0
- `dom-testing-library` version: 3.12.2
- `react` version: 16.8.2
- `node` version: 11.10.0

If I look at the docs for the query APIs, every function has `container` as the first parameter (https://testing-library.com/docs/api-queries#bytext). This parameter is autobound when we call `render` so this parameter should be removed from the docs.

**Comment by alexkrolick** [comment]
DOM testing library does not autobind by default. This is a feature of react-testing-library which is documented in the `render` docs: https://testing-library.com/docs/react-testing-library/api#render

**Comment by akatechis** [comment]
Fair enough, I think I must have clicked the "API" link that is above the Wrappers section on the left side, which took me to the DTL docs and I didn't notice that it was not RTL-specific.

**Comment by alexkrolick** [comment]
Feel free to file an issue or PR to improve the organization in the docs repo: https://github.com/alexkrolick/testing-library-docs

This one might make navigating between sections a bit better: https://github.com/alexkrolick/testing-library-docs/issues/40
