### ISSUE TITLE
Add typescript definitions for findBy* queries

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/dom-testing-library#226]
I don't trust myself with typing those, so if someone would be good enough to do that, I would appreciate it!

**Comment by alexkrolick** [comment]
Pretty sure it's `Promise<HTMLElement | Error>`, `Promise<HTMLElement[] | Error>`

**Comment by JaxCavalera** [comment]
I put together the type definitions for findBy and findAllBy queries,  but am unable to commit due to:
```
Stashing changes... [started]
Stashing changes... [skipped]
→ No partially staged files found...
Running linters... [started]
Running tasks for README.md [started]
Running tasks for README.md [skipped]
→ No staged files match README.md
Running tasks for *.+(js|jsx|json|yml|yaml|css|less|scss|ts|tsx|md|graphql|mdx) [started]
Running tasks for *.+(js|jsx|json|yml|yaml|css|less|scss|ts|tsx|md|graphql|mdx) [failed]
→ .\node_modules\kcd-scripts\dist\index.js could not be found. Try `npm install .\node_modules\kcd-scripts\dist\index.js`.

Running linters... [failed]
→ .\node_modules\kcd-scripts\dist\index.js could not be found. Try `npm install .\node_modules\kcd-scripts\dist\index.js`.
.\node_modules\kcd-scripts\dist\index.js could not be found. Try `npm install .\node_modules\kcd-scripts\dist\index.js`.

husky > pre-commit hook failed (add --no-verify to bypass)
Completed with errors, see above.
```
I could bypass the pre-commit as running lint locally passes, same with `npm run validate`. Running `npm run setup` passes everything except 1 test and this turned out to be due to my machine running a little slower than the test allocated for:
```diff
   container.setAttribute('data-test-attribute', 'something changed twice')
-  await skipSomeTimeForMutationObserver(50)
+  await skipSomeTimeForMutationObserver(200)

   expect(callback).toHaveBeenCalledTimes(3)
```
Thoughts?

**Comment by kentcdodds** [comment]
Thanks to @JaxCavalera, this has been resolved.

**Comment by bopfer** [comment]
This may be a naive question, but why is `Error` a possible return value for findBy* queries?  It pretty much negates the convenience of using them over "waitForElement + getBy*".  Now, I have to check to make sure the return was not `Error` before I can use the element.  I guess I can make my own wrapper for that, but I was just curious.

**Comment by alexkrolick** [comment]
It shouldn't return an error, it returns a Promise that can reject with an error (which throws when used with async/await syntax)

**Comment by bopfer** [comment]
@alexkrolick, Hmm, maybe there is a discrepancy.  What you typed in the 2nd comment in this issue is not what is in the typings.  In the typings it is `Promise<HTMLElement> | Error`.  Which means for TypeScript to be happy in my tests I have to do:

```javascript
const btn = await findByText('add user');
if (btn instanceof HTMLElement) {
  // do the rest of the test
}
else {
  throw new Error(btn.message);
}
```

**Comment by alexkrolick** [comment]
If you're a Typescript user, care to make a PR to fix that?

**Comment by bopfer** [comment]
Will do.  I think the ` | Error` part should just be removed completely. Since the error will be thrown, an `Error` will never actually be returned.
