### ISSUE TITLE
Latest release (3.18.1) breaks labels with nested spans

### ISSUE THREAD

**Issue by NehrDani** [kentcdodds/dom-testing-library#230]
- `dom-testing-library` version: 3.18.1
- `react` version: 1.18.4
- `node` version: 10.15.2
- `npm` (or `yarn`) version:  yarn 1.15.2

### Relevant code or config:

```jsx
<div>
  <input id="some-id" />
  <label htmlFor="some-id">
    <span>Some Input</span>
  </label>
</div>
```

### What you did:

Just installed `react-testing-library` after cleaning up my `node_modules`.

### What happened:

All Tests using `getLabelById` with nested `spans` are failing.

### Reproduction:

https://codesandbox.io/s/0ym9qxzlmp

### Problem description:

Recently working tests are now failing without changes in the code or the tests.
Already mentioned here: https://github.com/kentcdodds/dom-testing-library/pull/190#issuecomment-474642984

**Comment by kentcdodds** [comment]
Honestly, I think the new behavior is problematic and probably never what we want. So I'm going to just revert it.
