### ISSUE TITLE
UMD bundle can't be loaded into browser

### ISSUE THREAD

**Issue by PabloDinella** [kentcdodds/dom-testing-library#234]
- `dom-testing-library` version: 3.17.0
- `react` version: N/A
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

### Relevant code or config:

```js
/**
 *  Simple node.js style script loader for modern browsers
 **/
function loadScript(src, cb) {
  var script = document.createElement('script');
  script.async = true;
  script.src = src;

  script.onerror = function() {
    cb(new Error("Failed to load" + src));
  };

  script.onload = function() {
    cb();
  };

  document.getElementsByTagName("head")[0].appendChild(script);
}
```

### What you did:

Trying to load DomTestingLibrary into the browser.

### What happened:

```
dom-testing-library.umd.js:7 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at dom-testing-library.umd.js:7
    at dom-testing-library.umd.js:4
    at dom-testing-library.umd.js:5
```

### Reproduction:

Run the config code above on the devtools and then:

```
loadScript('https://unpkg.com/dom-testing-library@3.17.0/dist/dom-testing-library.umd.js', () => {})
```

### Problem description:

Hello, I was just trying to use dom-testing-library directly in the browser, like @kentcdodds did in [this stream](https://www.youtube.com/watch?v=ttmvAm6esSc), but realized it works until the version 3.16.x of the library, starting from 3.17.0 I get the error above. Am I missing something or?

### Suggested solution:

I have no idea why this happens, found no relevant changes in the commits on the 3.17.0 version :(

**Comment by alexkrolick** [comment]
The UMD files are very different here:

https://unpkg.com/dom-testing-library@3.16.8/dist/dom-testing-library.umd.js
https://unpkg.com/dom-testing-library@3.17.0/dist/dom-testing-library.umd.js

The 3.16.8 one is an actual 154kb bundle but versions 3.17.0+ (current is 3.18.2) have a bunch of external references instead (~3kb).

I'm guessing since there is no lockfile, the package that provides the build command is now installing a newer verson and publishes incorrectly.

**Comment by PabloDinella** [comment]
You're right, `kcd-scripts` builds ok on version 0.48.0. I'm looking into [what changed in version 0.49.0](https://github.com/kentcdodds/kcd-scripts/compare/v0.48.0...v0.49.0) but didn't understand what's going on yet

**Comment by alexkrolick** [comment]
@kentcdodds related to #251. Change introduced at kcd-scripts 0.49.

**Comment by kentcdodds** [comment]
Whoops 😅 forgot about this one and opened the new one 😅
