### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by briandipalma** [kentcdodds/dom-testing-library#237]
### Describe the feature you'd like:

I'd like to add support for IE11.

### Suggested implementation:

Adding imports for two polyfills:

```javascript
import "element-matches";
import "events-polyfill";
```

events for `events.js` and matches for `get-node-text.js`

**Comment by kentcdodds** [comment]
Hi. Thanks for the issue.

I don't add polyfills in my libraries. I expect people to either use it in an environment that doesn't need to polyfill, or include the polyfill themselves.

You're welcome to contribute to the docs to add an IE11 section where this is described.
