### ISSUE TITLE
Add a function for printing a simple DOM representation for debugging

### ISSUE THREAD

**Issue by jlongster** [kentcdodds/dom-testing-library#24]
Would you be interested in a function like this? The only annoying thing I've found with using jsdom is that it's hard to debug if you don't know what's going on or are confused. In the browser you can just look at it, but you can't with jsdom. This gives me most of what I want:

```js
function prettyDOM(node, indent = 0) {
  let str = '';
  if (node) {
    str += ' '.repeat(indent) + (node.tagName || node.textContent) + '\n';
    for (let child of node.childNodes) {
      str += debugDOM(child, indent + 2);
    }
  }
  return str;
}
```

You can now do `console.log(prettyDOM(node))` and get an output like this in the terminal:

<img width="695" alt="screen shot 2018-04-18 at 9 36 57 pm" src="https://user-images.githubusercontent.com/17031/38966517-ae48e320-4350-11e8-917a-dca4feb9c7cb.png">

**Comment by jlongster** [comment]
Even better, add the attached testid to the output (and maybe allow the user to pass in specific attributes they want printed?):

```js
function debugDOM(node, indent = 0) {
  let str = '';
  if (node) {
    str += ' '.repeat(indent);
    if (node.tagName) {
      str += node.tagName + ' ' + (node.dataset['testid'] || '') + '\n';
    } else {
      str += node.textContent + '\n';
    }

    for (let child of node.childNodes) {
      str += debugDOM(child, indent + 2);
    }
  }
  return str;
}
```

<img width="587" alt="screen shot 2018-04-18 at 9 40 42 pm" src="https://user-images.githubusercontent.com/17031/38966614-2fce5614-4351-11e8-8a65-ccdedcdacadd.png">

**Comment by kentcdodds** [comment]
Perhaps we could expose this:

https://github.com/kentcdodds/dom-testing-library/blob/131a20bcc7cca4c0853acc49365a6c4746165471/src/queries.js#L150-L160

![dab5me1v4aaehlr](https://user-images.githubusercontent.com/1500684/38967293-f9e5a610-434b-11e8-835a-b2d81b0fd831.jpg)

What do you think?

**Comment by jlongster** [comment]
Yeah, that's probably good! I like seeing a more concise form, is there a way to customize it at all? I basically don't care about most of my attributes (and there is quite a bit in my dom, which makes it harder to read). It's not a big deal though, I'd be fine just using that function.

**Comment by gnapse** [comment]
@kentcdodds I can do it. Also, do you think it should publicly keep that name `htmlElementToDisplay`? I think I like something more along the lines of `debugDOM` above for the name.

**Comment by kentcdodds** [comment]
Thanks @gnapse! How about `prettyDOM` as suggested in @jlongster's util? Perhaps we could also expose a `logDOM(container)` as a shortcut to `console.log(prettyDOM(container))` 🤔

**Comment by Zirro** [comment]
This [custom formatter](https://github.com/jsdom/jsdom-devtools-formatter) and jsdom's [`serialize()` -function](https://github.com/jsdom/jsdom#serializing-the-document-with-serialize) may be of interest to you as well.

**Comment by kentcdodds** [comment]
I'm pretty happy with the `printDOM` API :+1:

I think I'd like to re-export it in react-testing-library :)
