### ISSUE TITLE
ByDataAttribute same as ByTestId but for any data attribute possible.

### ISSUE THREAD

**Issue by marcelmokos** [kentcdodds/dom-testing-library#244]
### Describe the feature you'd like:

**ByDataAttribute** same as **ByTestId** but for any data attribute possible.

- reason is that currently we are using both `data-testid` and `data-message-id` for locating our dom elements in tests.
- `data-message-id` are created by `react-intl` fork we have created https://www.npmjs.com/package/react-intl-with-data-message-id

### Suggested implementation:
```
const queryByDataAttribute = (
  container,
  text,
  ...args
) => {
  const dataAttribute = text.startsWith("data-") ? text : `data-${text}`;
  queryByAttribute(container, dataAttribute, ...args)
}

const queryAllByDataAttribute = (
  container,
  text,
  ...args
) => {
  const dataAttribute = text.startsWith("data-") ? text : `data-${text}`;
  queryAllByAttribute(container, dataAttribute, ...args)
}

export const findByDataAttribute = makeFinder(queryByDataAttribute)
export const findAllByDataAttribute = makeFinder(queryAllByDataAttribute)
```

Then export the `queryByDataAttribute`, `queryAllByDataAttribute`, `findByDataAttribute`, `findAllByDataAttribute` from `queries.js`

### Describe alternatives you've considered:

We were using Enzyme and we want to switch but we need this change for the transition. I was hoping for general function to query for custom attributes. There is `queryByAttribute` and `queryAllByAttribute` but they are not exported from the `dom-testing-library`.

### Teachability, Documentation, Adoption, Migration Strategy:

Please consider this proposal, I can work on the PR and I will add documentation as well. If you approve the idea for implementation.

**Comment by alexkrolick** [comment]
Adding a higher-level API would encourage using data attributes too much, which goes against the goal of providing accessible APIs that enable testing the app using the user interface. 

The queryByAttribute helper you are using is exported for exactly this use case - creating custom queries for specific libraries or patterns in your app. Instead of creating a generic data-attribute query, expose something like "getByMessageId" which has an agreed-upon meaning  in the context of your app.

**Comment by marcelmokos** [comment]
I will have to try to use query(All)ByAttribute in our tests. I do not want to encourage using invisible data attributes.

Every app we are creating is using more than one language and we default to use `react-intl` for any text on the page. Since translations are not one of the responsibilities of the dev team we started using `data-message-id` as a solution that works well with testing and CMS admin.

**Comment by alexkrolick** [comment]
Instead of using queryAllByAttribute directly in tests I would make a custom query and custom render:

- https://testing-library.com/docs/dom-testing-library/api-helpers#custom-queries
- https://testing-library.com/docs/react-testing-library/setup#custom-render
