### ISSUE TITLE
Support `debug` inside `within` API

### ISSUE THREAD

**Issue by renerbaffa** [kentcdodds/dom-testing-library#249]
### Describe the feature you'd like:

Usually you want to test components positioned high up in the three to get closer to the real user interaction possible (integrating child components) and it can make the DOM tree very long. Due to that, sometimes is hard to find/debug specific parts of the DOM only using the `debug` method provided by the `render` API.

The `within` API is very helpful to find elements inside a specific container of the DOM but it does not return a `debug` method to help developers to see/debug that specific part of the DOM you are interested on.

### Suggested implementation:

It wold be very nice to extend the `within` API, providing `debug` method so that it helps developers to debug only part of the DOM tree. I thought of adding this method in the `getQueriesForElement` (https://github.com/kentcdodds/dom-testing-library/blob/master/src/get-queries-for-element.js). That was the only solution that came into my mind so far.

### Describe alternatives you've considered:

Currently I am doing that like this:

```javascript
import { react, prettyDOM } from 'react-testing-library'
const renderedElement = render(<MyComponent />)


console.log(prettyDOM(renderedElement.getByTestId('some-test-id')))
```

I could also extend the `within` API in my project to return that kind of function. Both options would work just fine but I thought it would be a nice idea to extend the `within` API to support such feature.

### Teachability, Documentation, Adoption, Migration Strategy:

The sintax I had in mind was something like this:

```javascript
import { within } from 'react-testing-library'
const renderedElement = render(<MyComponent />)



// Here is the suggestion
const { debug, getByText } = within(renderedElement.getByTestId('some-test-id'))
expect(getByText('my-assertion')).toBeInTheDocument() // some assertions
debug() // This would print in the terminal only the container we targeted rather than the hole tree
```

**Comment by kentcdodds** [comment]
I'm good with this 👍 PRs welcome.

**Comment by kentcdodds** [comment]
See the PR comments.
