### ISSUE TITLE
getAllBy* matchers?

### ISSUE THREAD

**Issue by alexkrolick** [kentcdodds/dom-testing-library#27]
* `dom-testing-library` version: 2.1.1

It looks like all the matchers are designed to return the first element matching a query. Would it make sense to also export matchers that return all of the matching nodes as well (e.g., `document.querySelectorAll` vs `document.querySelector`)? Some use cases are testing the length or sort order of lists, handling pagination, etc.

**Comment by kentcdodds** [comment]
Yes, I can see the value of this and done have asked me about it, so sure, I'd accept a pull request for it 👍
