### ISSUE TITLE
Add typings for the use with TypeScript

### ISSUE THREAD

**Issue by InExtremaRes** [kentcdodds/dom-testing-library#36]
Well, I think there is no much to say. At this time [react-testing-library](https://github.com/kentcdodds/react-testing-library) has a file for [typings](https://github.com/kentcdodds/react-testing-library/blob/1dfcd73de884c4411af5ce29fe23c19f845e459d/typings/index.d.ts).

Is there any plans to add some for this project?

Best regards.

**Comment by alexkrolick** [comment]
[Yes](https://github.com/kentcdodds/react-testing-library/issues/76#issuecomment-386851236)

@maddijoyce

**Comment by InExtremaRes** [comment]
Oh, thank you. I was looking for a file or an issue in this project and never thought to look there.

**Comment by maddijoyce** [comment]
Yep, I'm working on this at the moment, I'll be updating soon.

**Comment by InExtremaRes** [comment]
I am sorry. Will it include types for the `jest-dom` custom matchers?

**Comment by maddijoyce** [comment]
At this stage, I haven't but I can look into it.

**Comment by InExtremaRes** [comment]
[Here](https://github.com/gnapse/jest-dom#using-with-typescript) are some tips for augment `jest` namespace with the matcher's types. I guess the typings could go that way and do the merge declaration when importing (but I'm not very familiar with namespaces augmentation).

**Comment by gnapse** [comment]
Actually, regarding jest-dom and typescript, I was thinking that there must be something better to be done than what's described in the README of that repo. I attempted to do something [here](/gnapse/jest-dom/pull/11) and would greatly appreciate the review of someone here more knowledgeable of typescript, before I merge it.

**Comment by gnapse** [comment]
Doesn't this library has [typings](https://github.com/kentcdodds/dom-testing-library/tree/master/typings) already? I think this issue can be closed.
