### ISSUE TITLE
wait-for-expect dependency throws Unknown plugin "@babel/proposal-class-properties"

### ISSUE THREAD

**Issue by ericchernuka** [kentcdodds/dom-testing-library#38]
* `dom-testing-library` version: 2.2.0
* `react-testing-library` version: 3.0.2
* `react` version: 16.3.1
* `node` version: v8.9.4
* `npm` (or `yarn`) version: 6.0.0

### What you did:
Upon updating to the latest version of react-testing-library I now receive the following error when running `npm test`

### What happened:

```
    ReferenceError: Unknown plugin "@babel/proposal-class-properties" specified in "/Users/ec/Payload/payload/node_modules/dom-testing-library/node_modules/wait-for-expect/.babelrc" at 0, attempted to resolve relative to "/Users/ec/Payload/payload/node_modules/dom-testing-library/node_modules/wait-for-expect"

      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)
```

### Problem description:
I'm not entirely sure if this a config issue on my end or with the `wait-for-expect` package within dom-testing-library, but I decided to ask here first.

**Comment by lgandecki** [comment]
Very weird, could you remove your node_modules and package-lock.json and run npm install again?

**Comment by ericchernuka** [comment]
Removed both node_modules and package-lock.json and it still seems to happen.

**Comment by lgandecki** [comment]
I don't understand why jest is trying to read .babelrc from there - you shouldn't be "babeling" your node_modules. 

But, at the same time, we shouldn't have the .babelrc there in the first place in the npm package anyway, only in the sources, so I will tweak that.

**Comment by lgandecki** [comment]
No problem. Please let us know what you find :-)

You might need to put. "wait-for-expect": "0.6.2" in your devDependencies to force using that particular version

**Comment by ericchernuka** [comment]
After fixing what I believe was a jest configuration problem and doing a fresh npm install I no longer receive this error. Thanks for all your help.
