### ISSUE TITLE
data-original-title support for getByTitle

### ISSUE THREAD

**Issue by npeterkamps** [kentcdodds/dom-testing-library#46]
### Describe the feature you'd like:

Many tooltip libraries remove the `title` attribute and add `data-original-title` with the same value. I'm using [tippy.js](https://atomiks.github.io/tippyjs/). [Bootstrap](https://getbootstrap.com/docs/4.0/components/tooltips/) does this too.

Is this something that `getByTitle` should support out of the box?

### Teachability, Documentation, Adoption, Migration Strategy:

```js
// <span data-original-title="Tooltip message" id="2" />
const elementWithTooltip = getByTitle(container, 'Tooltip message')
```

**Comment by kentcdodds** [comment]
Thanks for the issue @npeterkamps. I don't think we should add this as it is not enough of a convention to warrant it. This is a situation where the cost of bloat to the library isn't worth the benefit of helping the few people who use libraries like the one you're suggesting.

That said, building this yourself should be pretty simple and that's the recommended way forward. Thanks!
