### ISSUE TITLE
Helper for testing style rules

### ISSUE THREAD

**Issue by oliverjam** [kentcdodds/dom-testing-library#56]
### Describe the feature you'd like:
Would you be interested in adding a helper for checking style rules? I taught a workshop on testing using the library and ended up with students stuck trying to check (for example) a button's background-colour had correctly changed.

Getting a DOM element's style rules is kind of gross, it so might be nice to expose a util like `getStyleValue`.

### Suggested implementation:

It could be as simple as:

```js
function getStyleValue(element, property) {
  return window.getComputedStyle(element).getPropertyValue(property);
}
```
If this is beyond the scope/doesn't fit the philosophy of the library then feel free to close ❤️

**Comment by kentcdodds** [comment]
Hi @oliverjam!

Check out the [`toHaveStyle`](https://github.com/gnapse/jest-dom#tohavestyle) assertion in [`jest-dom`](https://github.com/gnapse/jest-dom) :+1:
