### ISSUE TITLE
Merge wait and waitForElement

### ISSUE THREAD

**Issue by hnordt** [kentcdodds/dom-testing-library#57]
To simplify the `wait()` API I think we could merge `wait()` and `waitForElement()`.

The implementation would be something like:

```js
const isElement = obj => obj && obj.nodeType === Node.ELEMENT_NODE 

function wait(callback = () => {}) {
  const result = callback()
  return isElement(result) ? waitForElement(callback) : waitForExpect(callback)
}
```

**Comment by kentcdodds** [comment]
I'm in support of this 👍 thoughts from others? I think I'd accept a PR for this.

**Comment by hnordt** [comment]
@kentcdodds sure, I can submit a PR, I'll just wait for thoughts from other people.

**Comment by sompylasar** [comment]
`waitForElement` has quite a few options (and could be more to come) that are specifically about the DOM:
```ts
function waitForElement<T>(
  callback?: () => T | null | undefined,
  options?: {
    container?: HTMLElement
    timeout?: number
    mutationObserverOptions?: MutationObserverInit
  },
): Promise<T>
```
`wait` has a different set of options:
```ts
function wait(
  callback?: () => void,
  options?: {
    timeout?: number
    interval?: number
  },
): Promise<void>
```

**Comment by hnordt** [comment]
@sompylasar I don't see any problem on it because they are just optional options, when you provide the `callback` you are returning an element anyway, so you know that you can pass `container` or `mutationObserverOptions` as options.

It's also very easy to validate if the passed option is allowed in the context. The trade-off is an easier API.

**Comment by antoaravinth** [comment]
I see good points from @hnordt. We are using react-test-utils in a project and honestly I think we can have a single `wait` API exposed, as a result we will get an easier API. Its good to hide the implementation details like `waitForElement` inside `wait`.

**Comment by hnordt** [comment]
Closed due to https://github.com/kentcdodds/dom-testing-library/pull/58#issuecomment-398217658
