### ISSUE TITLE
getByAltText doesn't work with space in text

### ISSUE THREAD

**Issue by hipstersmoothie** [kentcdodds/dom-testing-library#61]
* `dom-testing-library` version: current
* `react` version: 16.4.1
* `node` version: 9.11.1
* `npm` (or `yarn`) version: 1.6.0

### Relevant code or config:

```js
const Button = () => (
	<button
	  alt="Menu Toggle"
	>
	  <span aria-hidden="true" />
	  <span aria-hidden="true" />
	  <span aria-hidden="true" />
	</button>
)
```

```js
test('hamburger toggles menu', () => {
  const { getByAltText } = render(
    <Button />
  );
  expect(getByAltText('Menu Toggle')).toBeDefined();
});
```

### Problem description: Should be able to find by alt text with spaces.

`getByAltText('Menu Toggle')` doesn't find the element
`getByAltText('Menu')` finds the element

**Comment by gnapse** [comment]
In believe `getByAltText` only works with the type of elements that support having an `alt` attribute, and `button` does not seem one of those. Check [its documentation](https://github.com/kentcdodds/dom-testing-library#getbyalttext) for details. Also according to [the code](https://github.com/kentcdodds/dom-testing-library/blob/275496f7dac2b25aed1ab3f83ffafa105d4e083b/src/queries.js#L141) it should not be finding a `button` element at all.

Now that does not explain how it did find the button in your code in some situations. Nor does this confirms if it really has a bug anyway regarding having a space in the text.

**Comment by hipstersmoothie** [comment]
I think i was misreading the output. sorry for the noise!

**Comment by atav32** [comment]
Yup,  `getByAltText` only queries `<img>`, `<input>`, and `<area>` tags, per its [documentation](https://testing-library.com/docs/dom-testing-library/api-queries#byalttext)

Also ran into this because I didn't realize that the SVG spec didn't include an `alt` attribute.

**Comment by edikamy** [comment]
expect(container.querySelector('[alt="Menu Toggle"]')).toBeInTheDocument()
