### ISSUE TITLE
Remove extend-expect

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/dom-testing-library#69]
People should know their abstractions and it doesn't make sense to me that we have this here. Instead people should `import 'jest-dom/extend-expect'`.

Doing this will help people know where they should go to learn about that abstraction.

This will be a breaking change.

**Comment by antoaravinth** [comment]
@kentcdodds  So we can have a plan for the same? May be we need to add deprecated warning first and then remove?

**Comment by kentcdodds** [comment]
I don't think it'd be worth the deprecation warning. Migrating away from this will be really easy.

**Comment by gnapse** [comment]
I'll take this.
