### ISSUE TITLE
Add support for `<title>` element in SVG with `getByTitle`

### ISSUE THREAD

**Issue by wyze** [kentcdodds/dom-testing-library#83]
### Describe the feature you'd like:

There is a `<title>` element that can be rendered within an SVG element, see [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title), and would be nice to be considered when doing a `getByTitle` assertion. Currently it does work with `getByText`, but that might be incorrect considering it behaves more like a title attribute than text content.

If accepted, I will work up a PR adding support for it.

### Suggested implementation:

Would need to find the `<title>` element and ensure it's parent is a `<svg>` element and allow that to be included in the assertion.

### Describe alternatives you've considered:

We currently use `getByText` as a selector.

**Comment by kentcdodds** [comment]
Yes, that sounds super! I'd definitely accept a PR for this added functionality :+1: Thank you!
