### ISSUE TITLE
"Safe" click event helper that warns when clicking non-interactive elements

### ISSUE THREAD

**Issue by alexkrolick** [kentcdodds/dom-testing-library#90]
### Describe the feature you'd like:

I was recently debugging an issue where I passed "container" to `fireEvent.click()` instead of a button reference. What if there was a variant of `fireEvent` that warns/errors when firing events on elements that aren't normally interactable? `button` and `a` would be safe, plus any semantic/`aria-` elements.

API ideas:

```
fireEvent.clickSafe(element, options)
fireEvent.accessibleClick(element, options)
fireEvent.click(element, { allowAny: true })
```

### Suggested implementation:

Detect target element tag name and attributes when firing events

### Teachability, Documentation, Adoption, Migration Strategy:

This would be a non-breaking change

**Comment by kentcdodds** [comment]
Hmmm... I'm really conflicted here. I really like the idea, but I don't want to add friction to using the library. Perhaps if we had a really helpful error message.

What if we did this:

```js
fireEvent.click(someDiv)
// throws an error that says something like: "Firing a click event on a non-clickable element is not recommended as it's not accessible. If you must, you can use `forceClick` instead."
```

Then people could do:

```js
fireEvent.forceClick(someDiv)
```

And that would work.

We'll want to make sure that we define a "clickable" element as one that's clickable/focusable as defined by the browser.

Thoughts?

**Comment by sompylasar** [comment]
You may want to take some inspiration from Cypress, it implements this concept of Actionability. https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Actionability

I really wish Cypress exported some of their DOM manipulation code as reusable libraries... We're really doing the same things here.

**Comment by alexkrolick** [comment]
I'd be more inclined to export it as `fireEvent.accessibleClick` than breaking the current click, at least through one release cycle? `.forceClick` seems reasonable in the long run, except maybe conflicting with the concept of "force click" on Mac touchpads.

So... what are the criteria for clickability? We can collect them here and see what the code would need to do.

**Comment by sompylasar** [comment]
@alexkrolick 

> So... what are the criteria for clickability? We can collect them here and see what the code would need to do.

> Checks and Actions Performed
> 
> 1. Scroll the element into view.
> 2. Ensure the element is not hidden.
> 3. Ensure the element is not disabled.
> 4. Ensure the element is not animating.
> 5. Ensure the element is not covered.
> 6. Scroll the page if still covered by an element with fixed position.
> 7. Fire the event at the desired coordinates.
>
> Whenever Cypress cannot interact with an element, it could fail at any of the above steps. You will usually get an error explaining why the element was not found to be actionable.

**Comment by alexkrolick** [comment]
Sounds like they mostly care about visual attributes, not the difference between a div and a button. We'd want to make that distinction somehow.

**Comment by alexkrolick** [comment]
The cypress actionability module actually is open source: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee

**Comment by alexkrolick** [comment]
Also, a lot of the time I rely on event bubbling to propagate a click from some inner span up to a button or other element; this would probably break that. Would it be possible to do something like detect that a click event was not handled by anything instead of allowing only certain elements? I don't know if React's event model would be compatible with that approach.

```
fireEvent.click(someDiv);
// Warning: click event was not handled
```

**Comment by sompylasar** [comment]
> The cypress actionability module actually is open source: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee

Yes, but you cannot `yarn add @cypress/actionability` to reuse that piece in `dom-testing-library` or your tests.

**Comment by sompylasar** [comment]
> Sounds like they mostly care about visual attributes, not the difference between a div and a button. We'd want to make that distinction somehow.

I don't think we want to make that distinction. You can make a perfectly valid accessible div with an onClick that shouldn't be any different from a button from the actionability perspective.

**Comment by kentcdodds** [comment]
Yeah, I don't think there's anything we're going to do about this one. Closing.
